### ISSUE TITLE
release clarification

### ISSUE THREAD

**Issue by jubalh** [boothj5/libmesode#13]
Hi,

I understood it like libmesode will always be at the same stage as libstrophe, just without the windows stuff.
I saw that libstrophe has a release 0.9.2 out since a while. Any plans about libmesode?

**Comment by Neustradamus** [comment]
@jubalh: Always diff at this time?
What is missing yet?

**Comment by pasis** [comment]
@Neustradamus, there is no development in libmesode. All releases are just merges with libstrophe. There are a lot of conflicts, so merging process consumes much time. With code refactoring commit it will be near to impossible to support libmesode. Personally I would vote not to support it and backport only recent bugfixes without new features.

**Comment by Neustradamus** [comment]
It is not possible to import features in libstrophe?
Comparaison of the old libstrophe code and libmesode at a moment...

**Comment by jubalh** [comment]
Yes that is the goal. We plan to port the good stuff from libmesode to libstrophe. And then deprecate libmesode.
People have limited time though.

**Comment by DebXWoody** [comment]
Go for it? What is the good stuff?

**Comment by jubalh** [comment]
@DebXWoody what do you mean?

What needs to be done is to backport the features that are in libmesode but not in libstrophe back into libstrophe.
You can talk to @pasis if you want to help.

**Comment by pasis** [comment]
The only difference with libstrophe is that libmesode provides callback to review certificate and manually trust it or not. Libstrophe doesn't ask user anything and validates (or rejects) certificates automatically depending on provided flags.

After implementing something similar in libstrophe we can deprecate libmesode completely. The thing is that I would like to see a similar feature in libstrophe which would be implemented properly: supported (or at least works correctly with a stub) in all TLS modules, new API is in the same style as the rest API, etc.

libstrophe is a general-purpose library, we need to provide features that would work for all applications, not break existing users and be backward-compatible.

**Comment by jubalh** [comment]
libmesode got deprecated, see https://github.com/profanity-im/libmesode/commit/8e5c8b32c7c36f471df0ac67ce0cdac6e8b30569
