### ISSUE TITLE
Switch to 0.10.0 version

### ISSUE THREAD

**Issue by lgremy** [boothj5/libmesode#19]
Hi,
In the `configure.ac` file, the version number is still `AC_INIT([libmesode], [0.9.3], [boothj5web@gmail.com])`, instead of I suppose `AC_INIT([libmesode], [0.10.0], [boothj5web@gmail.com])` according to the tag number of the master branch. Is it correct to switch to this version number, which seems to be required by profanity?
Thanks for your job on both pieces of software!

**Comment by jubalh** [comment]
> Is it correct to switch to this version number, which seems to be required by profanity?

Oh! Indeed you are right. Sorry for the mistake. Will fix it soon!

> Thanks for your job on both pieces of software!

Thanks for the positive feedback :)

**Comment by jubalh** [comment]
Done!

https://github.com/profanity-im/libmesode/commit/a3d894f2626bd2d97dfae03ca924782ce850294e
https://github.com/profanity-im/libmesode/releases/tag/0.10.1
