### ISSUE TITLE
Logging xmpp_send_raw

### ISSUE THREAD

**Issue by boothj5** [boothj5/libmesode#4]
When the following function is called, the stanza is not logged as with `xmpp_send()` and `xmpp_send_raw_string()`

```
void xmpp_send_raw(xmpp_conn_t * const conn, const char * const data, const size_t len);
```

Add this to upstream (libstrophe) and merge to libmesode.

**Comment by jubalh** [comment]
libmesode got deprecated, see https://github.com/profanity-im/libmesode/commit/8e5c8b32c7c36f471df0ac67ce0cdac6e8b30569
