### ISSUE TITLE
bashisms(?) in configure.ac result in syntax error in configure script

### ISSUE THREAD

**Issue by arvedarved** [boothj5/libmesode#7]
Attached is  a patch that make configure work with FreeBSD's /bin/sh

[patch-configure.ac.txt](https://github.com/boothj5/libmesode/files/753332/patch-configure.ac.txt)

**Comment by arvedarved** [comment]
Got a report that the patch is still incomplete, will try to work on a better patch.

**Comment by pasis** [comment]
Fixed by d5540fe6969768a4d5d3111b4691581461239e80. See #11.
