### ISSUE TITLE
X509 struct is opaque

### ISSUE THREAD

**Issue by dchokola** [boothj5/libmesode#9]
Libmesode fails to build on systems where the X509 struct is opaque in OpenSSL.

I wrote a hideous patch, attached.
[openssl.patch.txt](https://github.com/boothj5/libmesode/files/846350/openssl.patch.txt)

**Comment by boothj5** [comment]
Thanks, there's also a pull request #8 I'll take a look at both.

**Comment by boothj5** [comment]
Merged to master
